apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: operators-root
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/tunakirkoc/homelab.git
    targetRevision: main
    path: clusters/talos/operators
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
