apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portainer
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://portainer.github.io/k8s/
    chart: portainer
    targetRevision: 2.33.3
    helm:
      releaseName: portainer
      values: |
        enterpriseEdition:
          enabled: true
          image:
            tag: lts
        service:
          type: ClusterIP
        tls:
          force: true
        ingress:
          enabled: true
          ingressClassName: nginx-internal
          annotations:
            nginx.ingress.kubernetes.io/backend-protocol: HTTPS
            cert-manager.io/cluster-issuer: letsencrypt-prod
          hosts:
            - host: portainer.k8s.kirkoc.net
              paths:
                - path: /
          tls:
            - secretName: portainer-tls
              hosts:
                - portainer.k8s.kirkoc.net
  destination:
    server: https://kubernetes.default.svc
    namespace: portainer
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true