apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: penpot-db
  labels:
    app: penpot
spec:
  instances: 1
  storage:
    size: 1Gi
  bootstrap:
    initdb:
      database: penpot
      owner: penpot