apiVersion: v1
kind: Namespace
metadata:
  name: minecraft
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: bluemap-cluster
  namespace: minecraft
spec:
  instances: 1
  storage:
    size: 10Gi
  managed:
    services:
      disabledDefaultServices: ["ro", "r"]
      additional:
        - selectorType: rw
          serviceTemplate:
            metadata:
              name: "bluemap-cluster-external-rw"
              annotations:
                metallb.universe.tf/loadBalancerIPs: 10.0.5.85
            spec:
              type: LoadBalancer
